
SET(GUI_FILES
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.h
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddMapping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddMapping.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddMapping.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogExtractInfos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogExtractInfos.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogExtractInfos.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogFillAiPrompts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogFillAiPrompts.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogFillAiPrompts.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogReviewAiDesc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogReviewAiDesc.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogReviewAiDesc.ui
    ${CMAKE_CURRENT_LIST_DIR}/WidgetAdDescription.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetAdDescription.h
    ${CMAKE_CURRENT_LIST_DIR}/WidgetAdDescription.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogPossibleValues.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogPossibleValues.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogPossibleValues.ui
)
